name: 'Commit SVN'
description: 'Effettua il commit della repository su SVN'
author: 'favoloso'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  dry-run:
    description: "Esegue l'operazione senza committare."
    default: false
  svn-username:
    description: 'Username SVN'
    required: true
  svn-password:
    description: 'Password SVN'
    required: true
  svn-url:
    description: 'URL della repository SVN'
    required: true
  svn-path:
    description: "Path all'interno repository SVN"
    default: 'trunk'
  package-json-path:
    description: 'Path del package.json da cui estrarre la versione'
    default: 'package.json'
  commit-message:
    description: 'Messaggio del commit (placeholder: %version%, %sha%)'
    default: 'Rilascio %version%'
  allow-git-files:
    description: 'Consente di committare su SVN anche i file di Git'
    default: false  
runs:
  using: 'composite'
  steps:
    - id: deploy
      env:
        INPUT_SVN_USERNAME: ${{ inputs.svn-username }}
        INPUT_SVN_PASSWORD: ${{ inputs.svn-password }}
        INPUT_SVN_URL: ${{ inputs.svn-url }}
        INPUT_SVN_PATH: ${{ inputs.svn-path }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
        INPUT_ALLOW_GIT_FILES: ${{ inputs.allow-git-files }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        INPUT_PACKAGE_JSON_PATH: ${{ inputs.package-json-path }}
      run: |
        npx zx ${{ github.action_path }}/deploy.mjs
      shell: bash